
redis:
  password: 1234
  sentinel:
    master: mymaster
    nodes:
      - host: redis-sentinel1
        port: 26379
      - host: redis-sentinel2
        port: 26379
      - host: redis-sentinel3
        port: 26379

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

kakao:
  api:
    authorization: ${KAKAO_CLIENT_ID}


resilience4j:
  circuitbreaker:
    failure-rate-threshold: 10   # 실패 10% 이상 시 서킷 오픈
    slow-call-duration-threshold: 500   # 500ms 이상 소요 시 실패로 간주
    slow-call-rate-threshold: 10   # slowCallDurationThreshold 초과 비율이 10% 이상 시 서킷 오픈
    wait-duration-in-open-state: 30000   # OPEN -> HALF-OPEN 전환 전 기다리는 시간
    minimum-number-of-calls: 50   # 집계에 필요한 최소 호출 수
    sliding-window-size: 100   # 서킷 CLOSE 상태에서 N회 호출 도달 시 failureRateThreshold 실패 비율 계산
    permitted-number-of-calls-in-half-open-state: 30   # HALFOPEN -> CLOSE or OPEN 으로 판단하기 위해 호출 횟수

management:
  endpoints:
    web:
      base-path: /api/actuator
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true