redis:
  password: 1234
  master:
    host: localhost
    port: 6379

  slaves:
    - host: localhost
      port: 7001
    - host: localhost
      port: 7002
    - host: localhost
      port: 7003

kakao:
  api:
    authorization: ${KAKAO_CLIENT_ID}
